// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { StartTime, StartTimeTableId } from "./tables/StartTime.sol";
import { CloseTime, CloseTimeTableId } from "./tables/CloseTime.sol";
import { BaseTime, BaseTimeTableId } from "./tables/BaseTime.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { PlayerEntity, PlayerEntityTableId } from "./tables/PlayerEntity.sol";
import { Balance, BalanceTableId } from "./tables/Balance.sol";
import { MiningEquipment, MiningEquipmentTableId } from "./tables/MiningEquipment.sol";
import { MiningLevel, MiningLevelTableId } from "./tables/MiningLevel.sol";
import { MiningWork, MiningWorkTableId } from "./tables/MiningWork.sol";
import { MiningFarms, MiningFarmsTableId } from "./tables/MiningFarms.sol";
