// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMiningFarmSystem {
  error LibMiningFarm__FarmAlreadyUse(bytes32 farmEntity);
  error LibMiningFarm__FarmAlreadyFinish(bytes32 farmEntity);
  error LibMiningFarm__InvalidLevel(bytes32 farmEntity);
}
