// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITimeSystem {
  function startTime(bytes32 farmEntity) external returns (uint256);

  function closeTime(bytes32 farmEntity) external returns (uint256);

  function executeBaseTime(bytes32 farmEntity) external returns (uint256 baseTime);
}
